version: '3'

services:
    app:
        container_name: apeak3
        image: kaepa3/apeak3:latest
        build:
            context: .
            args:
              - NODE_TAG=12.8
              - NGINX_TAG=alpine
        environment:
            - NODE_ENV=production
        ports:
            - 80:80
            - 443:443
        restart: always
