version: '3'

services:
    app:
        container_name: apeak3
        image: apeak3:latest
        build:
            context: .
            args:
              - NODE_TAG=12.8
              - NGINX_TAG=alpine
        environment:
            - NODE_ENV=production
        ports:
            - 8080:80
        restart: always
